# Generated by Django 3.2.7 on 2021-09-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('describe', models.CharField(max_length=200)),
                ('input', models.CharField(max_length=200)),
                ('function_name', models.CharField(max_length=30)),
                ('result', models.CharField(max_length=200)),
                ('date', models.DateField(blank=True, default=None)),
            ],
        ),
    ]
