# Generated by Django 3.2.8 on 2021-10-15 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RssReader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, max_length=250)),
                ('limit', models.SmallIntegerField(blank=True)),
                ('format', models.CharField(choices=[('J', 'Json'), ('H', 'HTML'), ('P', 'PDF')], default='Json', max_length=10)),
                ('date_req', models.DateField(auto_now_add=True)),
                ('date_from_db', models.DateField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Rssreaders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
