# Generated by Django 3.2.8 on 2021-10-17 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_rssreader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rssreader',
            name='format',
            field=models.CharField(choices=[('json', 'json'), ('html', 'html'), ('pdf', 'pdf')], default='Json', max_length=10),
        ),
    ]
