# Generated by Django 3.2.8 on 2021-10-17 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0003_alter_rssreader_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rssreader',
            name='date_from_db',
            field=models.DateField(blank=True),
        ),
    ]
